version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    allow:
      # Internal gems
      - dependency-name: "govuk*"
        dependency-type: direct
      - dependency-name: gds-api-adapters
        dependency-type: direct
      - dependency-name: govspeak
        dependency-type: direct
      - dependency-name: plek
        dependency-type: direct
      - dependency-name: rubocop-govuk
        dependency-type: direct
      - dependency-name: slimmer
        dependency-type: direct
      # Framework gems
      - dependency-name: minitest
        dependency-type: direct
      - dependency-name: rails
        dependency-type: direct
      - dependency-name: sassc-rails
        dependency-type: direct

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    allow:
      # Internal packages
      - dependency-name: stylelint-config-gds
        dependency-type: direct
      # Framework packages
      - dependency-name: standardx
        dependency-type: direct
      - dependency-name: stylelint
        dependency-type: direct
      - dependency-name: jasmine-browser-runner
        dependency-type: direct
      - dependency-name: jasmine-core
        dependency-type: direct
