api_version: 1
auto_merge:
  - dependency: gds-api-adapters
    allowed_semver_bumps:
      - patch
      - minor
  - dependency: gds_zendesk
    allowed_semver_bumps:
      - patch
      - minor
  - dependency: govuk_app_config
    allowed_semver_bumps:
      - patch
      - minor
  - dependency: govspeak
    allowed_semver_bumps:
      - patch
      - minor
  - dependency: govuk_publishing_components
    allowed_semver_bumps:
      - patch
  - dependency: govuk_schemas
    allowed_semver_bumps:
      - patch
      - minor
  - dependency: govuk_test
    allowed_semver_bumps:
      - patch
      - minor
  - dependency: rubocop-govuk
    allowed_semver_bumps:
      - patch
      - minor
