---
- code: "3371ccf8123dfadf"
  name: fully_vaccinated
  option_text: "I will be fully vaccinated using an approved COVID-19 vaccine 14 or more days before I travel"
- code: "e9e286f8822bc330"
  name: vaccine_trial
  option_text: "Iâ€™m taking part in an approved COVID-19 vaccine trial"
- code: "529202127233d442"
  name: exemption_from_vaccination
  option_text: "I cannot have a COVID-19 vaccination for a medical reason approved by a clinician"
- code: "9ddc7655bfd0d477"
  name: unvaccinated
  option_text: "None of the above"
