- section_name: "Tax"
  title: "Register for Corporation Tax"
  description: "You need to register within 3 months of starting to do business, if you have not done so already."
  url: "https://www.gov.uk/corporation-tax"
- section_name: "Licences and registration"
  title: "Check if you need any licences for your business"
  description: "You might need licences or to register your company, depending on the type of work you do."
  url: "https://www.gov.uk/licence-finder/"
- section_name: "Insurance"
  title: "Check if you need insurance"
  description: "There are different types of insurance you might need, depending on your area of business."
  url: "https://www.abi.org.uk/products-and-issues/choosing-the-right-insurance/business-insurance/"
- section_name: "Tax"
  title: "Check if you need to send a Self Assessment"
  description: "You might need to send a tax return if you have any untaxed income, such as dividends."
  url: "https://www.gov.uk/check-if-you-need-tax-return"
- section_name: "Competition law"
  title: "Avoid anti-competitive activity"
  description: "You need to understand rules around price-fixing and competition."
  url: "https://www.gov.uk/cartels-price-fixing/types-of-anticompetitive-activity"
- section_name: "Data protection"
  title: "Learn how to deal with personal information"
  description: "If your business stores anyone's personal information, you need to know how to look after it."
  url: "https://www.gov.uk/data-protection-your-business"
- section_name: "Health and safety"
  title: "Health and safety at work"
  description: "How to keep your employees and customers safe."
  url: "https://www.hse.gov.uk/guidance/index.htm"
- section_name: "Running a business"
  title: "How to run a limited company"
  description: "Your responsibilities when running a limited company."
  url: "https://www.gov.uk/running-a-limited-company"
- section_name: "Running a business"
  title: "Starting a business overview"
  description: "General guidance about starting and growing your business"
  url: "https://www.gov.uk/browse/business/setting-up"
- section_name: "Running a business"
  title: "Include your company details on stationery"
  description: "Make sure you include your company details on any stationery and promotional materials."
  url: "https://www.gov.uk/running-a-limited-company/signs-stationery-and-promotional-material"
- section_name: "Help and support"
  title: "Get help from the Business Support Helpline"
  description: "Speak to the helpline to get advice for your business."
  url: "https://www.gov.uk/business-support-helpline"
- section_name: "Help and support"
  title: "Sign up for Companies House email reminders"
  description: "[TBC]"
  url: "https://www.gov.uk/guidance/register-for-email-reminders-from-companies-house"
- section_name: "Tax"
  title: "Register for VAT"
  description: "You need to register your business for VAT if your VAT taxable turnover is more than £85,000, if you have not already."
  url: "https://www.gov.uk/vat-registration"
- section_name: "Tax"
  title: "Check if you'll need to register for VAT"
  description: "If your turnover goes over £85,000, you need to register for VAT."
  url: "https://www.gov.uk/vat-registration/when-to-register"
- section_name: "Employing people"
  title: "Check what to do before employing someone"
  description: "What you need to know about to employing people."
  url: "https://www.gov.uk/get-ready-to-employ-someone"
- section_name: "Financial help"
  title: "Apply for a 'Start Up' loan"
  description: "Get a loan of between £500 to £25,000 to help get your business started."
  url: "https://www.gov.uk/apply-start-up-loan"
- section_name: "Financial help"
  title: "See what finance and support is available"
  description: "Look for support, based on where you are, your industry and size."
  url: "https://www.gov.uk/business-finance-support?business_stages%5B%5D=not-yet-trading"
- section_name: "Financial help"
  title: "Get financial support to help grow your business"
  description: "Look through different sources of funding, including grants and loans."
  url: "https://www.gov.uk/growing-your-business/get-extra-funding"
- section_name: "Financial help"
  title: "Get financial support during coronavirus"
  description: "You might be able to get financial support if your business has been affected by coronavirus."
  url: "https://www.gov.uk/business-coronavirus-support-finder"
- section_name: "Business location"
  title: "Check if you need to pay business rates"
  description: "You might need to pay business rates, depending on what sort of work you do at home."
  url: "https://www.gov.uk/introduction-to-business-rates/working-at-home"
- section_name: "Business location"
  title: "Show a sign where your business operates"
  description: "[TBC]"
  url: "https://www.gov.uk/running-a-limited-company/signs-stationery-and-promotional-material"
- section_name: "Employing people"
  title: "Guidance on employing people"
  description: "Read through the rules on employment and looking after your staff."
  url: "https://www.gov.uk/browse/employing-people"
- section_name: "Business location"
  title: "Check the rules on running a business from home"
  description: "You might need extra permissions or insurance when you run your business from home."
  url: "https://www.gov.uk/run-business-from-home"
- section_name: "Business location"
  title: "Find out about rules for business premises"
  description: "[TBC]"
  url: "https://www.gov.uk/browse/business/premises-rates"
- section_name: "Buying and selling"
  title: "How to buy items from abroad"
  description: "Rules you need to follow when importing items into the UK."
  url: "https://www.gov.uk/import-goods-into-uk"
- section_name: "Buying and selling"
  title: "How to sell items abroad"
  description: "Rules you need to follow when exporting items out of the UK."
  url: "https://www.gov.uk/export-goods"
- section_name: "Buying and selling"
  title: "How to sell items and services online"
  description: "Rules you need to follow if you want to sell items or services online."
  url: "https://www.gov.uk/online-and-distance-selling-for-businesses/online-selling"
- section_name: "Tax"
  title: "How and when to charge VAT"
  description: "The rules you need to follow once you're registered for VAT"
  url: "https://www.gov.uk/vat-businesses"
- section_name: "Tax"
  title: "You can register for VAT if you want to"
  description: "You do not have to register for VAT, because your turnover will be less than £85,000"
  url: "https://www.gov.uk/vat-registration/when-to-register"
