---
- start_date: 2012-01-01
  end_date: 2013-01-31
  max: "12,900"
  rate: 430
- start_date: 2013-02-01
  end_date: 2014-04-05
  max: "13,500"
  rate: 450
- start_date: 2014-04-06
  end_date: 2015-04-05
  max: "13,920"
  rate: 464
- start_date: 2015-04-06
  end_date: 2016-04-05
  max: "14,250"
  rate: 475
- start_date: 2016-04-06
  end_date: 2017-04-05
  max: "14,370"
  rate: 479
- start_date: 2017-04-06
  end_date: 2018-04-05
  max: "14,670"
  rate: 489
- start_date: 2018-04-06
  end_date: 2019-04-05
  max: "15,240"
  rate: 508
- start_date: 2019-04-06
  end_date: 2020-04-05
  max: "15,750"
  rate: 525
- start_date: 2020-04-06
  end_date: 2021-04-05
  max: "16,140"
  rate: 538
- start_date: 2021-04-06
  end_date: 2022-04-05
  max: "16,320"
  rate: 544
- start_date: 2022-04-06
  end_date: 2023-04-05
  max: "17,130"
  rate: 571
