# This Smart Answer can use rates from the start of year (this year - 4),
# so to keep it tidy please delete anything earlier than that, but make
# sure you keep (in practise) the 6 most recent entries, or whatever covers
# the required period.
---
- start_date: 2019-04-06
  end_date: 2020-04-05
  max: "16,410"
  rate: 547
- start_date: 2020-04-06
  end_date: 2021-04-05
  max: "16,800"
  rate: 560
- start_date: 2021-04-06
  end_date: 2022-04-05
  max: "16,980"
  rate: 566
- start_date: 2022-04-06
  end_date: 2023-04-05
  max: "17,820"
  rate: 594
- start_date: 2023-04-06
  end_date: 2024-04-05
  max: "20,070"
  rate: 669
- start_date: 2024-04-06
  end_date: 2025-04-05
  max: "21,870"
  rate: 729
