# Uses historical data at the moment, so only add items
# to this, do not remove them.
---
- start_date: 2010-04-06
  end_date: 2011-04-05
  lower_earning_limit_rate: 97
  ssp_weekly_rate: 79.15

- start_date: 2011-04-06
  end_date: 2012-04-05
  lower_earning_limit_rate: 102
  ssp_weekly_rate: 81.60

- start_date: 2012-04-06
  end_date: 2013-04-05
  lower_earning_limit_rate: 107
  ssp_weekly_rate: 85.85

- start_date: 2013-04-06
  end_date: 2014-04-05
  lower_earning_limit_rate: 109
  ssp_weekly_rate: 86.70

- start_date: 2014-04-06
  end_date: 2015-04-05
  lower_earning_limit_rate: 111
  ssp_weekly_rate: 87.55

- start_date: 2014-04-06
  end_date: 2017-04-05
  lower_earning_limit_rate: 112
  ssp_weekly_rate: 88.45

- start_date: 2017-04-06
  end_date: 2018-04-05
  lower_earning_limit_rate: 113
  ssp_weekly_rate: 89.35

- start_date: 2018-04-06
  end_date: 2019-04-05
  lower_earning_limit_rate: 116
  ssp_weekly_rate: 92.05

- start_date: 2019-04-06
  end_date: 2020-04-05
  lower_earning_limit_rate: 118
  ssp_weekly_rate: 94.25

- start_date: 2020-04-06
  end_date: 2021-04-05
  lower_earning_limit_rate: 120
  ssp_weekly_rate: 95.85

- start_date: 2021-04-06
  end_date: 2022-04-05
  lower_earning_limit_rate: 120
  ssp_weekly_rate: 96.35

- start_date: 2022-04-06
  end_date: 2023-04-05
  lower_earning_limit_rate: 123
  ssp_weekly_rate: 99.35

- start_date: 2023-04-06
  end_date: 2024-04-05
  lower_earning_limit_rate: 123
  ssp_weekly_rate: 109.40

- start_date: 2024-04-06
  end_date: 2025-04-05
  lower_earning_limit_rate: 123
  ssp_weekly_rate: 116.75
